/**
 * Phase E — the generic bridge between Phase D's procedural 3D jewellery engine
 * (`@/lib/jewellery-3d-generator`) and the EXISTING Live AR camera pipeline. This is
 * the ONLY module in the whole runtime that is category/item-aware in the sense of
 * "which items currently have a 3D asset" -- and even that is a plain DATA lookup
 * (`GLTF_3D_ASSET_REGISTRY`), never a rendering/transform/attachment branch. Every
 * function below is generic over ANY `Gltf3dAssetMetadata`; nothing here contains
 * `if (jewelleryId === "diamond-choker")` or a choker-specific code path.
 *
 * WHY A REGISTRY, NOT A NEW DATABASE COLUMN: the catalogue schema has no 3D-asset
 * storage yet (confirmed by Phase A's direct schema audit, unchanged since --
 * `docs/jewellery-3d-asset-spec.md` §5 documents the target shape for whichever
 * milestone adds it). `resolveGltf3dAssetMetadata` is the SAME lookup a database
 * query would perform once that column exists -- swapping this in-memory map for a
 * real query later requires no change to any other function in this file, or to
 * `useLiveArSession.ts`'s call sites, which only ever call `resolveGltf3dAssetMetadata`/
 * `loadLive3dJewelleryAsset`, never read the registry directly.
 *
 * HOW THE EXISTING M6.8 3D FOUNDATION IS REUSED, UNCHANGED: `createThreeRenderer`/
 * `createThreeScene`/`addRestrainedLighting`/`applyEnvironmentLighting`/
 * `createThreeCamera`/`renderThreeFrame` (all from M6.8, all previously built but
 * never wired to a real call site) are called here exactly as designed, with zero
 * modification. `computeThreeJewelleryTransform` (three-transform.ts) is the ENTIRE
 * "coordinate mapping / scale-from-physical-dimensions / orientation" implementation
 * (Phase E Steps 8/9/10) -- this file adds no new geometry math, only the glue that
 * feeds it the EXISTING 2D pipeline's own already-smoothed, already-tracked output
 * (see `deriveScaleResultFromSmoothedTransform`'s doc comment below for exactly what
 * "reuse existing tracking smoothing" (Step 16) means here: this file introduces NO
 * new smoothing system at all -- it re-derives a `ScaleResult`/`RotationResult` shape
 * from the LiveTransform the EXISTING `TransformSmoother`/`TrackingStateMachine`
 * already produced this frame for the 2D sprite, so the 3D mesh inherits the exact
 * same smoothing characteristics for free).
 *
 * HONEST LIMITATION carried forward from M6.8 (three-types.ts's own file docstring):
 * the depth/perspective placement is DERIVED from the 2D pipeline's own validated
 * on-screen scale, not an independently calibrated 3D measurement -- there is no real
 * camera intrinsics or depth sensor anywhere in this pipeline. This file changes
 * nothing about that; it only finally exercises the math that was built to handle it.
 */
import * as THREE from "three";

import type { Gltf3dAssetMetadata } from "@/lib/live-ar/jewellery-representation";
import type { SurfaceOrientation } from "@/lib/live-ar/three/body-attachment";
import { cloneGltfInstance, loadGltfAsset } from "@/lib/live-ar/three/three-asset-loader";
import { buildCameraConfig, createThreeCamera, updateCameraForViewport } from "@/lib/live-ar/three/three-camera";
import { addRestrainedLighting, applyEnvironmentLighting, createThreeScene } from "@/lib/live-ar/three/three-scene";
import { createThreeRenderer, renderThreeFrame, resizeThreeRenderer } from "@/lib/live-ar/three/three-renderer";
import {
  composeJewelleryQuaternionFromEuler,
  computeMeshScaleFactor,
  computeThreeJewelleryTransform,
  computeVirtualDepthMm,
  unprojectScreenPointAtDepth,
} from "@/lib/live-ar/three/three-transform";
import type { ThreeCameraConfig, ThreeJewelleryTransform } from "@/lib/live-ar/three/three-types";
import type { CategorySlug, JewelleryAssetGeometry, LiveTransform, RotationResult, ScaleResult } from "@/lib/live-ar/types";

/**
 * The current, real state of "which vault items have a 3D asset": exactly one entry,
 * the Diamond Choker generated in Phase D (`apps/web/public/generated-3d-assets/
 * diamond-choker.glb`, regenerated by `apps/web/src/lib/jewellery-3d-generator/
 * generate-public-assets.test.ts`). Every field is either the Phase D
 * prototype-measurements spec's own already-labeled value or a direct pass-through --
 * nothing here invents a new number. `physicalWidthMm`/`physicalHeightMm`/
 * `physicalDepthMm` are `prototype_estimated`, NOT catalogue-verified (see
 * `docs/diamond-choker-prototype-measurements.json`) -- the live 3D transform below
 * is therefore only as physically accurate as that already-documented estimate.
 */
const GLTF_3D_ASSET_REGISTRY: Record<string, Gltf3dAssetMetadata> = {
  "b68b76b3-55ba-4808-869c-4d8266f7aff7": {
    modelUrl: "/generated-3d-assets/diamond-choker.glb",
    modelFormat: "glb",
    physicalWidthMm: 190,
    physicalHeightMm: 106,
    physicalDepthMm: 12,
    attachmentType: "neck_choker",
    anchor: { x: 0, y: 0, z: 0 },
    mirrorable: false,
    materialProfile: "pbr-metallic-roughness",
    scaleCorrection: null,
    rotationCorrectionDegrees: null,
  },
};

/** Generic lookup -- `null` for any id with no 3D asset yet (the overwhelming
 * majority of the vault today), which callers treat identically to "this item has no
 * gltf3dAsset" everywhere else in this codebase (`jewellery-representation.ts`'s
 * existing `resolveJewelleryRepresentation` contract) -- i.e. fall back to 2D. */
export function resolveGltf3dAssetMetadata(jewelleryId: string): Gltf3dAssetMetadata | null {
  return GLTF_3D_ASSET_REGISTRY[jewelleryId] ?? null;
}

/**
 * Phase E Step 6's generic attachment resolver: maps a free-text `attachmentType`
 * (the SAME convention `JewelleryAsset.attachment_point` already uses for the 2D
 * pipeline) onto which of this runtime's EXISTING tracked categories can drive it.
 * Deliberately prefix-based and data-driven, not an enum of specific values, so a
 * future `"neck_haaram"` or `"ear_drop"` resolves correctly with zero code changes.
 * Returns `null` for any attachment this runtime has no live tracking for yet
 * (`wrist_*`, `finger`, `forehead`, `nose` -- see docs/live-3d-jewellery-integration.md
 * for why a ring's `attachmentType` of `"finger"` correctly resolves to `null` here:
 * this runtime's `CategorySlug` union is only `"earrings" | "necklace"` today, a real,
 * pre-existing architectural fact, not something this phase invents or works around). */
export function attachmentTypeToTrackedCategory(attachmentType: string | null): CategorySlug | null {
  if (attachmentType === null) return null;
  if (attachmentType.startsWith("neck")) return "necklace";
  if (attachmentType.startsWith("ear")) return "earrings";
  return null;
}

export interface Live3dJewelleryAsset {
  metadata: Gltf3dAssetMetadata;
  /** Owned by this asset entry -- one clone per loaded item (three-asset-loader.ts's
   * existing cache/clone discipline: the underlying geometry/material/texture are
   * shared by reference with the cached master, never re-fetched per item). */
  instance: THREE.Group;
  /** The mesh's OWN authored bounding-box width (mm, per the asset-spec convention) --
   * used by `computeLive3dTransform` to rescale the mesh to the catalogue's real
   * `physicalWidthMm`, exactly as `computeMeshScaleFactor` (three-transform.ts,
   * unmodified) was always designed to. */
  boundingBoxWidthMm: number;
}

/** Loads (or reuses the cached) GLB for a specific, already-resolved metadata object
 * -- factored out from `loadLive3dJewelleryAsset` below SPECIFICALLY so it is
 * testable with a synthetic metadata object (e.g. pointing at a `data:` URL built
 * from a real generated GLB) without depending on the registry or a real HTTP fetch. */
export async function loadLive3dAssetFromMetadata(metadata: Gltf3dAssetMetadata): Promise<Live3dJewelleryAsset> {
  const loaded = await loadGltfAsset(metadata.modelUrl);
  const instance = cloneGltfInstance(loaded);
  const boundingBoxWidthMm = loaded.boundingBox.getSize(new THREE.Vector3()).x;
  return { metadata, instance, boundingBoxWidthMm };
}

/** The generic entry point `useLiveArSession.ts` calls whenever the selected
 * jewellery item changes: registry lookup, then load-through-the-existing-loader.
 * Returns `null` for any item with no registered 3D asset -- callers treat this
 * exactly like "no gltf3dAsset" everywhere else (2D fallback, Step 2). */
export async function loadLive3dJewelleryAsset(jewelleryId: string): Promise<Live3dJewelleryAsset | null> {
  const metadata = resolveGltf3dAssetMetadata(jewelleryId);
  if (!metadata) return null;
  return loadLive3dAssetFromMetadata(metadata);
}

/**
 * Pure. Derives the minimal `ScaleResult` shape `computeThreeJewelleryTransform`
 * actually reads (only `.success`/`.targetWidthPx` -- see three-transform.ts) FROM
 * the 2D pipeline's own already-smoothed `LiveTransform.scaleFactor`, by inverting
 * the SAME `scaleFactor = targetWidthPx / effectiveWidthPx` relationship
 * `computeScale` (geometry.ts, unmodified) used to produce it in the first place.
 * This is how "reuse existing tracking smoothing" (Step 16) is satisfied WITHOUT a
 * second smoothing system: the smoothing already happened, upstream, on
 * `scaleFactor` -- this function only undoes the one division needed to recover an
 * equivalent `targetWidthPx` for the 3D depth calculation. */
export function deriveScaleResultFromSmoothedTransform(smoothed: LiveTransform, assetGeometry: JewelleryAssetGeometry): ScaleResult {
  const effectiveWidthPx = assetGeometry.alphaBbox[2] - assetGeometry.alphaBbox[0];
  return {
    success: true,
    scaleFactor: smoothed.scaleFactor,
    targetWidthPx: smoothed.scaleFactor * effectiveWidthPx,
    usedPhysicalDimensions: true,
    method: "derived_from_smoothed_2d_transform",
  };
}

/** Pure. Same rationale as `deriveScaleResultFromSmoothedTransform` above, for
 * rotation -- only `.success`/`.rotationDegrees` are ever read from this by
 * `computeThreeJewelleryTransform`. */
export function deriveRotationResultFromSmoothedTransform(smoothed: LiveTransform): RotationResult {
  return { success: true, rotationDegrees: smoothed.rotationDegrees, rawDegrees: null, clamped: false, method: "derived_from_smoothed_2d_transform" };
}

/**
 * Pure. The actual coordinate-mapping/scale/orientation math (Phase E Steps 8/9/10) --
 * entirely `computeThreeJewelleryTransform` (three-transform.ts, unmodified, M6.8).
 * Returns `null` exactly when a physically meaningful placement cannot be computed:
 * either the 2D pipeline's own tracking failed this frame (mirrors
 * `computeThreeJewelleryTransform`'s own `!scale.success` case, which cannot actually
 * happen here since `deriveScaleResultFromSmoothedTransform` always reports success --
 * kept only because the underlying function's contract requires handling it), or this
 * asset has no `physicalWidthMm` at all (HONEST LIMITATION, Step 9: "if a physically
 * meaningful scale cannot be obtained... document the limitation rather than
 * inventing fake accuracy" -- there is nothing to derive a real-world scale from, so
 * this returns null rather than guessing one). */
export function computeLive3dTransform(
  smoothed: LiveTransform,
  asset: Live3dJewelleryAsset,
  assetGeometry: JewelleryAssetGeometry,
  yawAsymmetry: number,
  viewportWidthPx: number,
  viewportHeightPx: number,
  cameraConfig: ThreeCameraConfig
): ThreeJewelleryTransform | null {
  if (asset.metadata.physicalWidthMm === null) return null;
  const scale = deriveScaleResultFromSmoothedTransform(smoothed, assetGeometry);
  const rotation = deriveRotationResultFromSmoothedTransform(smoothed);
  return computeThreeJewelleryTransform(
    smoothed.anchorPx,
    scale,
    rotation,
    yawAsymmetry,
    asset.metadata.physicalWidthMm,
    asset.boundingBoxWidthMm,
    viewportWidthPx,
    viewportHeightPx,
    cameraConfig
  );
}

/** Pure. Mutates `instance`'s position/quaternion/scale in place from an
 * already-computed transform. Split out from `renderLive3dFrame` below specifically
 * so the actual transform application is unit-testable without a real WebGL context
 * (this repo's established M6.8 discipline: isolate the pure transformation math from
 * the unavoidably-GPU-dependent render call -- see three-renderer.ts's file
 * docstring). */
export function applyLive3dTransform(instance: THREE.Group, transform: ThreeJewelleryTransform): void {
  instance.position.set(transform.positionMm.x, transform.positionMm.y, transform.positionMm.z);
  instance.quaternion.set(transform.quaternion[0], transform.quaternion[1], transform.quaternion[2], transform.quaternion[3]);
  instance.scale.setScalar(transform.scale);
}

export interface ThreeLiveRuntime {
  renderer: THREE.WebGLRenderer;
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  /** Never attached to the DOM -- its pixels are composited onto the EXISTING main 2D
   * canvas (see renderer.ts's `compositeOccluded3dOverlay`), so there is still exactly
   * ONE visible canvas element, one mirror transform, one capture-frame call site
   * (Step 5: "do not create a second competing rendering engine"). */
  canvas: HTMLCanvasElement;
  currentInstance: THREE.Group | null;
}

/** Creates the persistent 3D runtime -- call exactly ONCE per Live AR session (Step
 * 17/20: never recreate the renderer/scene/camera per frame). Requires a real WebGL2
 * context; throws if unavailable (mirrors `createThreeRenderer`'s own contract) --
 * callers must catch this once and remember not to retry every frame (see
 * useLiveArSession.ts's `threeUnavailableRef`), falling back to 2D for the rest of
 * the session. */
export function createThreeLiveRuntime(): ThreeLiveRuntime {
  const canvas = document.createElement("canvas");
  const renderer = createThreeRenderer(canvas);
  const scene = createThreeScene();
  addRestrainedLighting(scene);
  applyEnvironmentLighting(scene, renderer);
  const camera = createThreeCamera(buildCameraConfig(1, 1));
  // applyEnvironmentLighting performs its own internal PMREM render passes, which
  // renderer.info accumulates like any other render call -- reset here so the first
  // real per-frame stats (Step 21's debug panel) reflect only the jewellery mesh
  // itself, not this one-time setup cost (a real, measured discrepancy found during
  // this phase's own real-browser verification -- see
  // docs/live-3d-jewellery-integration.md).
  renderer.info.reset();
  return { renderer, scene, camera, canvas, currentInstance: null };
}

/** Frees the renderer's GPU context. Call when the Live AR session ends entirely
 * (mirrors `disposeThreeRenderer`'s own existing convention), never per
 * jewellery-selection change (the loaded ASSET's own disposal is
 * `three-asset-loader.ts`'s `clearGltfAssetCache`, an entirely separate concern). */
export function disposeThreeLiveRuntime(runtime: ThreeLiveRuntime): void {
  runtime.renderer.dispose();
}

function ensureInstanceInScene(runtime: ThreeLiveRuntime, instance: THREE.Group): void {
  if (runtime.currentInstance === instance) return;
  if (runtime.currentInstance) runtime.scene.remove(runtime.currentInstance);
  runtime.scene.add(instance);
  runtime.currentInstance = instance;
}

/**
 * The one per-frame entry point. Positions the asset from the ALREADY-SMOOTHED 2D
 * transform (see this module's file docstring), renders exactly one Three.js frame,
 * and returns the rendered (transparent-background) canvas ready to composite -- or
 * `null` if no physically meaningful transform could be computed this frame (caller
 * falls back to the existing 2D sprite, unconditionally -- Step 2).
 *
 * REQUIRES A REAL WEBGL2 CONTEXT -- like `three-renderer.ts`'s own
 * `renderThreeFrame`, this is NOT exercised by `vitest run` (jsdom has no WebGL2).
 * The pure parts it delegates to (`computeLive3dTransform`/`applyLive3dTransform`)
 * ARE covered by `three-live-bridge.test.ts`; this function's actual WebGL output was
 * instead verified once, ad hoc, in a real browser -- see
 * docs/live-3d-jewellery-integration.md for exactly what that verification did and
 * did not cover.
 */
export function renderLive3dFrame(
  runtime: ThreeLiveRuntime,
  asset: Live3dJewelleryAsset,
  smoothed: LiveTransform,
  assetGeometry: JewelleryAssetGeometry,
  yawAsymmetry: number,
  viewportWidthPx: number,
  viewportHeightPx: number
): HTMLCanvasElement | null {
  updateCameraForViewport(runtime.camera, viewportWidthPx, viewportHeightPx);
  resizeThreeRenderer(runtime.renderer, viewportWidthPx, viewportHeightPx);
  const cameraConfig = buildCameraConfig(viewportWidthPx, viewportHeightPx);
  const transform = computeLive3dTransform(smoothed, asset, assetGeometry, yawAsymmetry, viewportWidthPx, viewportHeightPx, cameraConfig);
  if (!transform) return null;
  ensureInstanceInScene(runtime, asset.instance);
  applyLive3dTransform(asset.instance, transform);
  renderThreeFrame(runtime.renderer, runtime.scene, runtime.camera);
  return runtime.canvas;
}

/**
 * Phase F (docs/true-body-surface-jewellery-attachment.md) — the surface-attached
 * transform. `computeLive3dTransform`/`renderLive3dFrame` above are UNCHANGED (Phase
 * E's exact behavior, and their own existing tests still pass unmodified); this is a
 * new, separate function because Phase F's actual fix is a different ORIENTATION
 * source, not a different position/scale derivation.
 *
 * Position and scale are IDENTICAL to Phase E: the already-smoothed 2D anchor,
 * unprojected at the depth that matches the already-validated 2D on-screen scale
 * (`computeVirtualDepthMm`/`unprojectScreenPointAtDepth`, both unmodified), then
 * rescaled to the catalogue's physical width (`computeMeshScaleFactor`, unmodified).
 *
 * Orientation is the real fix: `orientation` (from `body-attachment.ts`'s
 * `resolveAttachmentOrientation`) carries a REAL yaw+pitch (from MediaPipe's own
 * facial transformation matrix, when available) and a real roll (shoulder-line
 * tilt) -- composed via `composeJewelleryQuaternionFromEuler`, never the old
 * pitch-always-0 `composeJewelleryQuaternion`.
 *
 * `physicalDepthMm`'s role (Step 11's "physically meaningful local attachment
 * offset"): the mesh's own LOCAL origin is nudged forward by HALF the item's own
 * authored depth, along whichever way the mesh is CURRENTLY oriented (the offset is
 * rotated by the SAME orientation quaternion, so it always points "out of the neck"
 * from the current perspective, never a fixed world direction) -- so the mesh's
 * BACK surface sits at the estimated attachment depth (approximating "resting on the
 * skin") rather than the mesh's CENTERLINE floating there. This is the asset's own
 * already-known `physicalDepthMm` (Phase D/E, e.g. 12mm for the Diamond Choker), not
 * an invented constant -- when it's null, the offset is simply 0 (no claim made).
 */
export function computeSurfaceAttachedTransform(
  smoothed: LiveTransform,
  asset: Live3dJewelleryAsset,
  assetGeometry: JewelleryAssetGeometry,
  orientation: SurfaceOrientation,
  viewportWidthPx: number,
  viewportHeightPx: number,
  cameraConfig: ThreeCameraConfig
): ThreeJewelleryTransform | null {
  if (asset.metadata.physicalWidthMm === null) return null;
  const scale = deriveScaleResultFromSmoothedTransform(smoothed, assetGeometry);
  if (!scale.success || scale.targetWidthPx === null) return null;

  const depthMm = computeVirtualDepthMm(asset.metadata.physicalWidthMm, scale.targetWidthPx, viewportHeightPx, cameraConfig.verticalFovDegrees);
  const basePositionMm = unprojectScreenPointAtDepth(smoothed.anchorPx, viewportWidthPx, viewportHeightPx, depthMm, cameraConfig);
  const quaternion = composeJewelleryQuaternionFromEuler(orientation.yawRadians, orientation.pitchRadians, orientation.rollRadians);

  const halfDepthMm = (asset.metadata.physicalDepthMm ?? 0) / 2;
  const localForward = new THREE.Vector3(0, 0, halfDepthMm).applyQuaternion(new THREE.Quaternion(quaternion[0], quaternion[1], quaternion[2], quaternion[3]));

  return {
    positionMm: { x: basePositionMm.x + localForward.x, y: basePositionMm.y + localForward.y, z: basePositionMm.z + localForward.z },
    quaternion,
    scale: computeMeshScaleFactor(asset.metadata.physicalWidthMm, asset.boundingBoxWidthMm),
  };
}

/**
 * Surface-attached counterpart to `renderLive3dFrame` above -- same WebGL2/renderer
 * plumbing, different transform source (`computeSurfaceAttachedTransform`, taking a
 * real `SurfaceOrientation` instead of a bare yaw scalar). This is the function
 * `useLiveArSession.ts` actually calls for the live necklace path as of Phase F.
 * NOT exercised by `vitest run` for the same real-WebGL2-required reason as
 * `renderLive3dFrame` -- see that function's own doc comment.
 */
export function renderSurfaceAttachedFrame(
  runtime: ThreeLiveRuntime,
  asset: Live3dJewelleryAsset,
  smoothed: LiveTransform,
  assetGeometry: JewelleryAssetGeometry,
  orientation: SurfaceOrientation,
  viewportWidthPx: number,
  viewportHeightPx: number
): HTMLCanvasElement | null {
  updateCameraForViewport(runtime.camera, viewportWidthPx, viewportHeightPx);
  resizeThreeRenderer(runtime.renderer, viewportWidthPx, viewportHeightPx);
  const cameraConfig = buildCameraConfig(viewportWidthPx, viewportHeightPx);
  const transform = computeSurfaceAttachedTransform(smoothed, asset, assetGeometry, orientation, viewportWidthPx, viewportHeightPx, cameraConfig);
  if (!transform) return null;
  ensureInstanceInScene(runtime, asset.instance);
  applyLive3dTransform(asset.instance, transform);
  renderThreeFrame(runtime.renderer, runtime.scene, runtime.camera);
  return runtime.canvas;
}
